class BrainShapeTemplate {
  constructor() {
    this.shape = [
      [__XXXXXXXXXXX__],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],

      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],

      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],

      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],

      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],

      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
      [XXXXXXXXXXXXXXX],
    ];
  }

}
